development:
  adapter: sqlite3
  database: db/development.sqlite3
test:
  adapter: sqlite3
  database: db/test.sqlite3
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see rails configuration guide
#   # http://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: 5
production:
  adapter: postgresql
  database: development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost